#   This file is part of Item List.

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

from PyQt5 import QtCore, QtGui, QtWidgets
from GetLanguage import Language
from os import path
import glob
import json

# Setting language variable
language = Language.Get()

# User interface code generated by PyQt5 UI code generator
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 120)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.langComboBox = QtWidgets.QComboBox(Dialog)
        self.langComboBox.setObjectName("langComboBox")
        self.gridLayout.addWidget(self.langComboBox, 0, 1, 1, 1)
        self.themeComboBox = QtWidgets.QComboBox(Dialog)
        self.themeComboBox.setObjectName("themeComboBox")
        self.gridLayout.addWidget(self.themeComboBox, 1, 1, 1, 1)
        self.langLabel = QtWidgets.QLabel(Dialog)
        self.langLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.langLabel.setObjectName("langLabel")
        self.gridLayout.addWidget(self.langLabel, 0, 0, 1, 1)
        self.themeLabel = QtWidgets.QLabel(Dialog)
        self.themeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.themeLabel.setObjectName("themeLabel")
        self.gridLayout.addWidget(self.themeLabel, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.langComboBox.currentIndexChanged.connect(self.changeLanguage)

    def retranslateUi(self, Dialog):
        global language
        language = Language.Get()
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", language.get("actionPreferences")))
        self.langLabel.setText(_translate("Dialog", language.get("language") + ":"))
        self.themeLabel.setText(_translate("Dialog", language.get("theme") + ":"))

        # Add list of available languages to langComboBox
        langlist = []
        for lang in glob.glob("langs/*.json"):
            langlist.append(path.basename(lang).replace(".json", ""))
        langlist.sort()
        langlist.insert(0, "System")
        self.langComboBox.addItems(langlist)

        # Load settings file for getting current language setting
        with open("settings.json", "r", encoding="UTF-8") as settingsfile:
            settings = json.load(settingsfile)
            
        # Select the current language setting on langComboBox
        self.langComboBox.setCurrentIndex(langlist.index(settings["language"]))
    
    def changeLanguage(self):
        settings = {
            "language": str(self.langComboBox.currentText()),
            "theme": "Default"
        }

        with open("settings.json", "w", encoding="UTF-8") as settingsfile:
            json.dump(settings, settingsfile)
